/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author nguyenta71300
 */
public class View extends javax.swing.JFrame
{

    /**
     * @return the btnDeleteContact
     */
    public javax.swing.JButton getBtnDeleteContact()
    {
        return btnDeleteContact;
    }

    /**
     * @return the btnEditContact
     */
    public javax.swing.JButton getBtnUndo()
    {
        return btnUndo;
    }

    /**
     * @return the btnSave
     */
    public javax.swing.JButton getBtnSave()
    {
        return btnSave;
    }

    /**
     * @return the mnuItemSave
     */
    public javax.swing.JMenuItem getMnuItemSave()
    {
        return mnuItemSave;
    }

    /**
     * @return the btnAddContact
     */
    public javax.swing.JButton getBtnAddContact()
    {
        return btnAddContact;
    }

    /**
     * @return the mnuItemOpen
     */
    public javax.swing.JMenuItem getMnuItemOpen()
    {
        return mnuItemOpen;
    }

    /**
     * Creates new form view
     */
    public View()
    {
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pmData = new javax.swing.JPopupMenu();
        pmItemOpen = new javax.swing.JMenuItem();
        pmItemSave = new javax.swing.JMenuItem();
        fileChooseOpen = new javax.swing.JFileChooser();
        lbData = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        btnAddContact = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnDeleteContact = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAddressBook = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuData = new javax.swing.JMenu();
        mnuItemOpen = new javax.swing.JMenuItem();
        mnuItemSave = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();

        pmItemOpen.setToolTipText("open");
        pmData.add(pmItemOpen);

        pmItemSave.setText("jMenuItem2");
        pmData.add(pmItemSave);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdressManager");

        lbData.setText("Data:");
        getContentPane().add(lbData, java.awt.BorderLayout.PAGE_END);

        panelTable.setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressverwaltung/icons/Save16.gif"))); // NOI18N
        btnSave.setToolTipText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar2.add(btnSave);

        btnAddContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressverwaltung/icons/Add16.gif"))); // NOI18N
        btnAddContact.setToolTipText("Add Contact");
        btnAddContact.setFocusable(false);
        btnAddContact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddContact.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnAddContact);

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressverwaltung/icons/Undo16.gif"))); // NOI18N
        btnUndo.setToolTipText("Undo");
        btnUndo.setFocusable(false);
        btnUndo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUndo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUndo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUndoActionPerformed(evt);
            }
        });
        jToolBar2.add(btnUndo);

        btnDeleteContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adressverwaltung/icons/Delete16.gif"))); // NOI18N
        btnDeleteContact.setToolTipText("Delete Contact");
        btnDeleteContact.setFocusable(false);
        btnDeleteContact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDeleteContact.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(btnDeleteContact);

        panelTable.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        tableAddressBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAddressBook.setComponentPopupMenu(pmData);
        jScrollPane2.setViewportView(tableAddressBook);

        panelTable.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTable, java.awt.BorderLayout.CENTER);

        mnuData.setText("File");

        mnuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemOpen.setText("Open");
        mnuItemOpen.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuItemOpenActionPerformed(evt);
            }
        });
        mnuData.add(mnuItemOpen);

        mnuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuItemSave.setText("Save");
        mnuItemSave.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuItemSaveActionPerformed(evt);
            }
        });
        mnuData.add(mnuItemSave);

        jMenuBar1.add(mnuData);

        mnuEdit.setText("Edit");
        jMenuBar1.add(mnuEdit);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuItemSaveActionPerformed
    {//GEN-HEADEREND:event_mnuItemSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemSaveActionPerformed

    private void mnuItemOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuItemOpenActionPerformed
    {//GEN-HEADEREND:event_mnuItemOpenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuItemOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveActionPerformed
    {//GEN-HEADEREND:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUndoActionPerformed
    {//GEN-HEADEREND:event_btnUndoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUndoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContact;
    private javax.swing.JButton btnDeleteContact;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUndo;
    private javax.swing.JFileChooser fileChooseOpen;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel lbData;
    private javax.swing.JMenu mnuData;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenuItem mnuItemOpen;
    private javax.swing.JMenuItem mnuItemSave;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPopupMenu pmData;
    private javax.swing.JMenuItem pmItemOpen;
    private javax.swing.JMenuItem pmItemSave;
    private javax.swing.JTable tableAddressBook;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lbData
     */
    public javax.swing.JLabel getLbData()
    {
        return lbData;
    }

    /**
     * @return the fileChooseOpen
     */
    public javax.swing.JFileChooser getFileChooseOpen()
    {
        return fileChooseOpen;
    }

    /**
     * @return the panelTable
     */
    public javax.swing.JPanel getPanelTable()
    {
        return panelTable;
    }

    /**
     * @return the tableAddressBook
     */
    public javax.swing.JTable getTableAddressBook()
    {
        return tableAddressBook;
    }
}
